// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AlwaysShowGitRepoPane
{
	internal sealed partial class Vsix
	{
		public const string Id = "AlwaysShowGitRepoPane.206d49e7-34bb-49bc-8751-90d96537a282";
		public const string Name = "AlwaysShowGitRepoPane";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "A. J. Henderson";
		public const string Tags = "";
	}
}
