// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace AlwaysShowGitRepoPane
{
	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		public const string AlwaysShowGitRepoPaneString = "ea5eb438-d835-492c-89b9-740b15d665ed";
		public static Guid AlwaysShowGitRepoPane = new Guid(AlwaysShowGitRepoPaneString);
	}
	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
	}
}